/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "78aa644faacd4d5bb9038654647b3ecf",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "78aa644faacd4d5bb9038654647b3ecf",
            "region": "eu-west-1"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://jrprvscsc5ffxmw6w3pg75else.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5x54zel2gvcynha4qe7efn5us4",
    "aws_cloud_logic_custom": [
        {
            "name": "poiapi",
            "endpoint": "https://bgsxzp0b7a.execute-api.eu-west-1.amazonaws.com/test",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:0cbe8811-66d1-478e-af11-7b3a85f71ad7",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_CKBuPpA2Z",
    "aws_user_pools_web_client_id": "3p47ofihslhosfpvs7grf4ij7v",
    "oauth": {
        "domain": "civiglioweb90af3ccd-90af3ccd-test.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://test.civiglio.it/",
        "redirectSignOut": "https://test.civiglio.it/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "adminlog-test",
            "region": "eu-west-1"
        },
        {
            "tableName": "civigliopoi-test",
            "region": "eu-west-1"
        },
        {
            "tableName": "media-test",
            "region": "eu-west-1"
        },
        {
            "tableName": "poi-test",
            "region": "eu-west-1"
        },
        {
            "tableName": "statistiche-test",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "civigliowebba8ebe1e07b047938f92b0cad411ac6f221800-test",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
